[resources]
git-tree-sha1 = "5c11f414b40e58e8ef42fab57656af15016a8380"

    [[resources.download]]
    sha256 = "1e991a6f743a450d4b69744cb1cc1c7388368e96af93b1e2edc1aacf743189be"
    url = "https://github.com/waralex/DashBootstrapComponents.jl/releases/download/v0.13.0+1/DashBootstrapComponentsResources.v0.13.0+1.tar.gz"
